services:
  - type: web
    name: walawi-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_DEBUG
        value: 0
      - key: SECRET_KEY
        generateValue: true
